Assignment 9: first attempt
enviro3/bloc-jams-angular pull request #2
Opened 2017-03-23 06:17 UTC by enviro3

-added thumb to the seek bar 
@droberts84

2017-03-23 12:48 UTC, drobtravels approved these changes
👍

2017-03-23 12:58 UTC, drobtravels requested changes
HINT: Checkout the CSS [left property](https://developer.mozilla.org/en-US/docs/Web/CSS/left)

2017-03-23 12:58 UTC, droberts84 commented on app/scripts/directives/seekBar.js
> +                    return {width: 10};
So this sets the thumbnail to always have a width 10 at all times.. but it stays in place.  Don't we want the thumb to move around as you drag your mouse?

2017-03-23 19:50 UTC, enviro3 commented on app/scripts/directives/seekBar.js
> +                    return {width: 10};
so, i'm playing with it and used ```left: 10```. I don't know how to make the thumb nail move with the percentage bar

2017-03-23 22:31 UTC, droberts84 commented on app/scripts/directives/seekBar.js
> +                    return {width: 10};
how do you make the percentage bar more?  Should left always be 10.. or will it need to change?

2017-03-24 12:37 UTC, droberts84 commented
:+1:

2017-03-24 15:41 UTC, merged